-- Seed ~90 paires de mots réparties par thème.

insert into public.word_pairs (word_fr_civil, word_fr_hors_theme, word_en_civil, word_en_hors_theme, theme)
values
  -- Général (18)
  ('chat', 'chien', 'cat', 'dog', 'general'),
  ('maison', 'appartement', 'house', 'apartment', 'general'),
  ('soleil', 'lune', 'sun', 'moon', 'general'),
  ('livre', 'journal', 'book', 'newspaper', 'general'),
  ('clé', 'serrure', 'key', 'lock', 'general'),
  ('lampe', 'bougie', 'lamp', 'candle', 'general'),
  ('horloge', 'calendrier', 'clock', 'calendar', 'general'),
  ('plante', 'fleur', 'plant', 'flower', 'general'),
  ('chaise', 'table', 'chair', 'table', 'general'),
  ('école', 'bureau', 'school', 'office', 'general'),
  ('voiture', 'vélo', 'car', 'bike', 'general'),
  ('arbre', 'buisson', 'tree', 'bush', 'general'),
  ('pluie', 'neige', 'rain', 'snow', 'general'),
  ('pont', 'tunnel', 'bridge', 'tunnel', 'general'),
  ('avion', 'bus', 'plane', 'bus', 'general'),
  ('robot', 'alien', 'robot', 'alien', 'general'),
  ('nuage', 'brouillard', 'cloud', 'fog', 'general'),
  ('montagne', 'colline', 'mountain', 'hill', 'general'),

  -- Animaux (18)
  ('lion', 'tigre', 'lion', 'tiger', 'animaux'),
  ('dauphin', 'requin', 'dolphin', 'shark', 'animaux'),
  ('papillon', 'abeille', 'butterfly', 'bee', 'animaux'),
  ('cheval', 'zèbre', 'horse', 'zebra', 'animaux'),
  ('pingouin', 'otarie', 'penguin', 'seal', 'animaux'),
  ('koala', 'panda', 'koala', 'panda', 'animaux'),
  ('grenouille', 'serpent', 'frog', 'snake', 'animaux'),
  ('souris', 'rat', 'mouse', 'rat', 'animaux'),
  ('hibou', 'aigle', 'owl', 'eagle', 'animaux'),
  ('poule', 'canard', 'chicken', 'duck', 'animaux'),
  ('baleine', 'orque', 'whale', 'orca', 'animaux'),
  ('loup', 'renard', 'wolf', 'fox', 'animaux'),
  ('chaton', 'chiot', 'kitten', 'puppy', 'animaux'),
  ('escargot', 'crabe', 'snail', 'crab', 'animaux'),
  ('chèvre', 'mouton', 'goat', 'sheep', 'animaux'),
  ('dromadaire', 'chameau', 'dromedary', 'camel', 'animaux'),
  ('pieuvre', 'méduse', 'octopus', 'jellyfish', 'animaux'),
  ('saumon', 'truite', 'salmon', 'trout', 'animaux'),

  -- Nourriture (18)
  ('pizza', 'burger', 'pizza', 'burger', 'nourriture'),
  ('pomme', 'banane', 'apple', 'banana', 'nourriture'),
  ('fromage', 'pain', 'cheese', 'bread', 'nourriture'),
  ('café', 'thé', 'coffee', 'tea', 'nourriture'),
  ('carotte', 'tomate', 'carrot', 'tomato', 'nourriture'),
  ('sushi', 'ramen', 'sushi', 'ramen', 'nourriture'),
  ('chocolat', 'vanille', 'chocolate', 'vanilla', 'nourriture'),
  ('croissant', 'gaufre', 'croissant', 'waffle', 'nourriture'),
  ('salade', 'soupe', 'salad', 'soup', 'nourriture'),
  ('citron', 'orange', 'lemon', 'orange', 'nourriture'),
  ('steak', 'poisson', 'steak', 'fish', 'nourriture'),
  ('yaourt', 'glace', 'yogurt', 'ice cream', 'nourriture'),
  ('eau', 'jus', 'water', 'juice', 'nourriture'),
  ('lait', 'milkshake', 'milk', 'milkshake', 'nourriture'),
  ('noisette', 'amande', 'hazelnut', 'almond', 'nourriture'),
  ('poivron', 'oignon', 'pepper', 'onion', 'nourriture'),
  ('miel', 'confiture', 'honey', 'jam', 'nourriture'),
  ('riz', 'pâtes', 'rice', 'pasta', 'nourriture'),

  -- Voyage (18)
  ('train', 'bateau', 'train', 'boat', 'voyage'),
  ('bus', 'taxi', 'bus', 'taxi', 'voyage'),
  ('avion', 'hélicoptère', 'plane', 'helicopter', 'voyage'),
  ('valise', 'sac à dos', 'suitcase', 'backpack', 'voyage'),
  ('hôtel', 'camping', 'hotel', 'camping', 'voyage'),
  ('plage', 'montagne', 'beach', 'mountain', 'voyage'),
  ('boussole', 'carte', 'compass', 'map', 'voyage'),
  ('phare', 'port', 'lighthouse', 'harbor', 'voyage'),
  ('métro', 'tram', 'subway', 'tram', 'voyage'),
  ('passeport', 'billet', 'passport', 'ticket', 'voyage'),
  ('tente', 'caravane', 'tent', 'caravan', 'voyage'),
  ('ski', 'surf', 'ski', 'surf', 'voyage'),
  ('désert', 'oasis', 'desert', 'oasis', 'voyage'),
  ('igloo', 'chalet', 'igloo', 'chalet', 'voyage'),
  ('musée', 'château', 'museum', 'castle', 'voyage'),
  ('marché', 'supermarché', 'market', 'supermarket', 'voyage'),
  ('tunnel', 'pont', 'tunnel', 'bridge', 'voyage'),
  ('vélo', 'trottinette', 'bike', 'scooter', 'voyage'),

  -- Objets (18)
  ('stylo', 'crayon', 'pen', 'pencil', 'objets'),
  ('ordinateur', 'tablette', 'computer', 'tablet', 'objets'),
  ('téléphone', 'appareil photo', 'phone', 'camera', 'objets'),
  ('lunettes', 'casque', 'glasses', 'headset', 'objets'),
  ('montre', 'bracelet', 'watch', 'bracelet', 'objets'),
  ('cadenas', 'clé usb', 'padlock', 'usb key', 'objets'),
  ('radiateur', 'ventilateur', 'heater', 'fan', 'objets'),
  ('télécommande', 'console', 'remote', 'console', 'objets'),
  ('aspirateur', 'balai', 'vacuum', 'broom', 'objets'),
  ('oreiller', 'couverture', 'pillow', 'blanket', 'objets'),
  ('bouteille', 'gourde', 'bottle', 'flask', 'objets'),
  ('panier', 'boîte', 'basket', 'box', 'objets'),
  ('parapluie', 'imperméable', 'umbrella', 'raincoat', 'objets'),
  ('marteau', 'tournevis', 'hammer', 'screwdriver', 'objets'),
  ('sac à main', 'porte-monnaie', 'handbag', 'wallet', 'objets'),
  ('horloge', 'sablier', 'clock', 'hourglass', 'objets'),
  ('ampoule', 'prise', 'bulb', 'socket', 'objets'),
  ('miroir', 'cadre', 'mirror', 'frame', 'objets');
