-- Remplace toutes les paires avec une nouvelle base (6 thèmes x 50 = 300).
-- Les thèmes utilisés : general, objets_quotidien, situations, nature, technologie, divertissement.

truncate table public.word_pairs restart identity;

insert into public.word_pairs (word_fr_civil, word_fr_hors_theme, word_en_civil, word_en_hors_theme, theme)
values
  -- Général (50)
  ('soleil', 'lune', 'sun', 'moon', 'general'),
  ('jour', 'nuit', 'day', 'night', 'general'),
  ('terre', 'ciel', 'earth', 'sky', 'general'),
  ('mer', 'montagne', 'sea', 'mountain', 'general'),
  ('ami', 'voisin', 'friend', 'neighbor', 'general'),
  ('amour', 'haine', 'love', 'hate', 'general'),
  ('joie', 'tristesse', 'joy', 'sadness', 'general'),
  ('calme', 'tempête', 'calm', 'storm', 'general'),
  ('force', 'faiblesse', 'strength', 'weakness', 'general'),
  ('liberté', 'prison', 'freedom', 'prison', 'general'),
  ('paix', 'guerre', 'peace', 'war', 'general'),
  ('lumière', 'ombre', 'light', 'shadow', 'general'),
  ('sourire', 'larme', 'smile', 'tear', 'general'),
  ('espoir', 'peur', 'hope', 'fear', 'general'),
  ('rapidité', 'lenteur', 'speed', 'slowness', 'general'),
  ('gain', 'perte', 'gain', 'loss', 'general'),
  ('succès', 'échec', 'success', 'failure', 'general'),
  ('début', 'fin', 'start', 'end', 'general'),
  ('question', 'réponse', 'question', 'answer', 'general'),
  ('secret', 'révélation', 'secret', 'revelation', 'general'),
  ('mémoire', 'oubli', 'memory', 'forgetfulness', 'general'),
  ('courage', 'prudence', 'courage', 'caution', 'general'),
  ('vérité', 'mensonge', 'truth', 'lie', 'general'),
  ('ordre', 'chaos', 'order', 'chaos', 'general'),
  ('vie', 'mort', 'life', 'death', 'general'),
  ('futur', 'passé', 'future', 'past', 'general'),
  ('silence', 'bruit', 'silence', 'noise', 'general'),
  ('reflet', 'miroir', 'reflection', 'mirror', 'general'),
  ('clé', 'serrure', 'key', 'lock', 'general'),
  ('porte', 'fenêtre', 'door', 'window', 'general'),
  ('route', 'chemin', 'road', 'path', 'general'),
  ('pont', 'tunnel', 'bridge', 'tunnel', 'general'),
  ('ville', 'village', 'city', 'village', 'general'),
  ('rêve', 'réalité', 'dream', 'reality', 'general'),
  ('fête', 'travail', 'party', 'work', 'general'),
  ('idée', 'projet', 'idea', 'project', 'general'),
  ('regard', 'voix', 'look', 'voice', 'general'),
  ('esprit', 'corps', 'mind', 'body', 'general'),
  ('bonheur', 'malheur', 'happiness', 'misfortune', 'general'),
  ('talent', 'effort', 'talent', 'effort', 'general'),
  ('nature', 'culture', 'nature', 'culture', 'general'),
  ('justice', 'injustice', 'justice', 'injustice', 'general'),
  ('énergie', 'repos', 'energy', 'rest', 'general'),
  ('instant', 'éternité', 'moment', 'eternity', 'general'),
  ('centre', 'périphérie', 'center', 'outskirts', 'general'),
  ('leader', 'suiveur', 'leader', 'follower', 'general'),
  ('cause', 'effet', 'cause', 'effect', 'general'),
  ('problème', 'solution', 'problem', 'solution', 'general'),
  ('rumeur', 'preuve', 'rumor', 'proof', 'general'),
  ('histoire', 'légende', 'story', 'legend', 'general'),

  -- Objets du quotidien (50)
  ('tasse', 'soucoupe', 'cup', 'saucer', 'objets_quotidien'),
  ('cuillère', 'fourchette', 'spoon', 'fork', 'objets_quotidien'),
  ('couteau', 'planche', 'knife', 'board', 'objets_quotidien'),
  ('assiette', 'bol', 'plate', 'bowl', 'objets_quotidien'),
  ('poêle', 'casserole', 'pan', 'pot', 'objets_quotidien'),
  ('couvercle', 'passoire', 'lid', 'colander', 'objets_quotidien'),
  ('éponge', 'liquide vaisselle', 'sponge', 'dish soap', 'objets_quotidien'),
  ('torchon', 'essuie-mains', 'dish towel', 'hand towel', 'objets_quotidien'),
  ('frigo', 'congélateur', 'fridge', 'freezer', 'objets_quotidien'),
  ('four', 'micro-ondes', 'oven', 'microwave', 'objets_quotidien'),
  ('grille-pain', 'bouilloire', 'toaster', 'kettle', 'objets_quotidien'),
  ('table', 'chaise', 'table', 'chair', 'objets_quotidien'),
  ('canapé', 'fauteuil', 'sofa', 'armchair', 'objets_quotidien'),
  ('oreiller', 'couverture', 'pillow', 'blanket', 'objets_quotidien'),
  ('drap', 'couette', 'sheet', 'duvet', 'objets_quotidien'),
  ('armoire', 'commode', 'wardrobe', 'dresser', 'objets_quotidien'),
  ('penderie', 'cintre', 'closet', 'hanger', 'objets_quotidien'),
  ('lavabo', 'robinet', 'sink', 'faucet', 'objets_quotidien'),
  ('douche', 'baignoire', 'shower', 'bathtub', 'objets_quotidien'),
  ('brosse à dents', 'dentifrice', 'toothbrush', 'toothpaste', 'objets_quotidien'),
  ('savon', 'shampoing', 'soap', 'shampoo', 'objets_quotidien'),
  ('serviette', 'gant', 'towel', 'washcloth', 'objets_quotidien'),
  ('rideau', 'tringle', 'curtain', 'rod', 'objets_quotidien'),
  ('fenêtre', 'volet', 'window', 'shutter', 'objets_quotidien'),
  ('clé', 'serrure', 'key', 'lock', 'objets_quotidien'),
  ('porte', 'poignée', 'door', 'handle', 'objets_quotidien'),
  ('interrupteur', 'ampoule', 'switch', 'bulb', 'objets_quotidien'),
  ('lampe', 'abat-jour', 'lamp', 'lampshade', 'objets_quotidien'),
  ('prise', 'multiprise', 'socket', 'power strip', 'objets_quotidien'),
  ('chargeur', 'câble', 'charger', 'cable', 'objets_quotidien'),
  ('téléphone', 'coque', 'phone', 'case', 'objets_quotidien'),
  ('ordinateur', 'clavier', 'computer', 'keyboard', 'objets_quotidien'),
  ('souris', 'tapis', 'mouse', 'mousepad', 'objets_quotidien'),
  ('écran', 'webcam', 'monitor', 'webcam', 'objets_quotidien'),
  ('télévision', 'télécommande', 'tv', 'remote', 'objets_quotidien'),
  ('enceinte', 'ampli', 'speaker', 'amp', 'objets_quotidien'),
  ('horloge', 'réveil', 'clock', 'alarm', 'objets_quotidien'),
  ('agenda', 'stylo', 'planner', 'pen', 'objets_quotidien'),
  ('cahier', 'crayon', 'notebook', 'pencil', 'objets_quotidien'),
  ('ciseaux', 'colle', 'scissors', 'glue', 'objets_quotidien'),
  ('ruban', 'agrafeuse', 'tape', 'stapler', 'objets_quotidien'),
  ('sac', 'portefeuille', 'bag', 'wallet', 'objets_quotidien'),
  ('parapluie', 'imperméable', 'umbrella', 'raincoat', 'objets_quotidien'),
  ('chaussure', 'chaussette', 'shoe', 'sock', 'objets_quotidien'),
  ('ceinture', 'boucle', 'belt', 'buckle', 'objets_quotidien'),
  ('manteau', 'écharpe', 'coat', 'scarf', 'objets_quotidien'),
  ('chapeau', 'lunettes de soleil', 'hat', 'sunglasses', 'objets_quotidien'),
  ('valise', 'cadenas', 'suitcase', 'lock', 'objets_quotidien'),
  ('bouteille', 'gourde', 'bottle', 'flask', 'objets_quotidien'),
  ('poubelle', 'sac poubelle', 'trash can', 'trash bag', 'objets_quotidien'),

  -- Situations (50)
  ('licenciement', 'embauche', 'firing', 'hiring', 'situations'),
  ('réunion', 'agenda', 'meeting', 'agenda', 'situations'),
  ('rendez-vous', 'médecin', 'appointment', 'doctor', 'situations'),
  ('examen', 'révision', 'exam', 'revision', 'situations'),
  ('voyage', 'billet', 'trip', 'ticket', 'situations'),
  ('déménagement', 'cartons', 'moving', 'boxes', 'situations'),
  ('mariage', 'cérémonie', 'wedding', 'ceremony', 'situations'),
  ('anniversaire', 'surprise', 'birthday', 'surprise', 'situations'),
  ('panne', 'dépannage', 'breakdown', 'repair', 'situations'),
  ('dispute', 'pardon', 'argument', 'forgiveness', 'situations'),
  ('négociation', 'contrat', 'negotiation', 'contract', 'situations'),
  ('réservation', 'hôtel', 'booking', 'hotel', 'situations'),
  ('inscription', 'formulaire', 'registration', 'form', 'situations'),
  ('présentation', 'public', 'presentation', 'audience', 'situations'),
  ('audition', 'musique', 'audition', 'music', 'situations'),
  ('casting', 'film', 'casting', 'movie', 'situations'),
  ('tournoi', 'finale', 'tournament', 'final', 'situations'),
  ('livraison', 'colis', 'delivery', 'package', 'situations'),
  ('grève', 'transport', 'strike', 'transport', 'situations'),
  ('retard', 'excuse', 'delay', 'excuse', 'situations'),
  ('urgence', 'secours', 'emergency', 'rescue', 'situations'),
  ('évacuation', 'incendie', 'evacuation', 'fire', 'situations'),
  ('check-in', 'aéroport', 'check-in', 'airport', 'situations'),
  ('queue', 'guichet', 'line', 'counter', 'situations'),
  ('contrôle', 'sécurité', 'check', 'security', 'situations'),
  ('garde', 'enfant', 'caretaking', 'child', 'situations'),
  ('babysitting', 'soirée', 'babysitting', 'evening', 'situations'),
  ('consultation', 'avocat', 'consultation', 'lawyer', 'situations'),
  ('atelier', 'bricolage', 'workshop', 'diy', 'situations'),
  ('stage', 'entreprise', 'internship', 'company', 'situations'),
  ('réunion', 'visioconférence', 'meeting', 'videoconference', 'situations'),
  ('brainstorming', 'post-it', 'brainstorm', 'sticky note', 'situations'),
  ('formation', 'diplôme', 'training', 'diploma', 'situations'),
  ('pot', 'départ', 'farewell', 'sendoff', 'situations'),
  ('collecte', 'dons', 'fundraiser', 'donations', 'situations'),
  ('alerte', 'météo', 'alert', 'weather', 'situations'),
  ('apprentissage', 'mentorat', 'learning', 'mentoring', 'situations'),
  ('débat', 'vote', 'debate', 'vote', 'situations'),
  ('fête', 'voisins', 'party', 'neighbors', 'situations'),
  ('randonnée', 'pause', 'hike', 'break', 'situations'),
  ('camping', 'feu de camp', 'camping', 'campfire', 'situations'),
  ('visite', 'musée', 'visit', 'museum', 'situations'),
  ('séance', 'cinéma', 'session', 'cinema', 'situations'),
  ('session', 'jeux', 'session', 'games', 'situations'),
  ('repas', 'partage', 'meal', 'sharing', 'situations'),
  ('entretien', 'annuel', 'review', 'annual', 'situations'),
  ('ticket', 'contrôle', 'ticket', 'inspection', 'situations'),
  ('quarantaine', 'test', 'quarantine', 'test', 'situations'),
  ('enquête', 'témoignage', 'investigation', 'testimony', 'situations'),
  ('concours', 'inscription', 'contest', 'signup', 'situations'),

  -- Nature (50)
  ('forêt', 'clairière', 'forest', 'clearing', 'nature'),
  ('rivière', 'cascade', 'river', 'waterfall', 'nature'),
  ('montagne', 'vallée', 'mountain', 'valley', 'nature'),
  ('désert', 'oasis', 'desert', 'oasis', 'nature'),
  ('plage', 'dune', 'beach', 'dune', 'nature'),
  ('lac', 'île', 'lake', 'island', 'nature'),
  ('volcan', 'cratère', 'volcano', 'crater', 'nature'),
  ('tempête', 'éclair', 'storm', 'lightning', 'nature'),
  ('ouragan', 'tornade', 'hurricane', 'tornado', 'nature'),
  ('pluie', 'arc-en-ciel', 'rain', 'rainbow', 'nature'),
  ('rosée', 'matin', 'dew', 'morning', 'nature'),
  ('neige', 'flocon', 'snow', 'snowflake', 'nature'),
  ('bourgeon', 'feuille', 'bud', 'leaf', 'nature'),
  ('racine', 'tronc', 'root', 'trunk', 'nature'),
  ('branche', 'fruit', 'branch', 'fruit', 'nature'),
  ('abeille', 'fleur', 'bee', 'flower', 'nature'),
  ('papillon', 'pollen', 'butterfly', 'pollen', 'nature'),
  ('chenille', 'cocon', 'caterpillar', 'cocoon', 'nature'),
  ('loup', 'meute', 'wolf', 'pack', 'nature'),
  ('renard', 'terrier', 'fox', 'den', 'nature'),
  ('ours', 'tanière', 'bear', 'den', 'nature'),
  ('cerf', 'bois', 'deer', 'antlers', 'nature'),
  ('oiseau', 'nid', 'bird', 'nest', 'nature'),
  ('poisson', 'récif', 'fish', 'reef', 'nature'),
  ('dauphin', 'vague', 'dolphin', 'wave', 'nature'),
  ('baleine', 'océan', 'whale', 'ocean', 'nature'),
  ('requin', 'aileron', 'shark', 'fin', 'nature'),
  ('corail', 'anémone', 'coral', 'anemone', 'nature'),
  ('étoile', 'galaxie', 'star', 'galaxy', 'nature'),
  ('lune', 'croissant', 'moon', 'crescent', 'nature'),
  ('comète', 'queue', 'comet', 'tail', 'nature'),
  ('marée', 'haute', 'tide', 'high', 'nature'),
  ('marée', 'basse', 'tide', 'low', 'nature'),
  ('geyser', 'source', 'geyser', 'spring', 'nature'),
  ('glacier', 'iceberg', 'glacier', 'iceberg', 'nature'),
  ('falaise', 'rocher', 'cliff', 'rock', 'nature'),
  ('grotte', 'stalactite', 'cave', 'stalactite', 'nature'),
  ('prairie', 'herbe', 'meadow', 'grass', 'nature'),
  ('champ', 'blé', 'field', 'wheat', 'nature'),
  ('savane', 'acacia', 'savanna', 'acacia', 'nature'),
  ('toundra', 'mousse', 'tundra', 'moss', 'nature'),
  ('canyon', 'ravin', 'canyon', 'ravine', 'nature'),
  ('crique', 'lagon', 'cove', 'lagoon', 'nature'),
  ('mangrove', 'racines', 'mangrove', 'roots', 'nature'),
  ('brise', 'alizé', 'breeze', 'trade wind', 'nature'),
  ('colibri', 'nectar', 'hummingbird', 'nectar', 'nature'),
  ('hérisson', 'piquants', 'hedgehog', 'spines', 'nature'),
  ('écureuil', 'gland', 'squirrel', 'acorn', 'nature'),
  ('grenouille', 'nénuphar', 'frog', 'water lily', 'nature'),
  ('champignon', 'spore', 'mushroom', 'spore', 'nature'),

  -- Technologies (50)
  ('ordinateur', 'smartphone', 'computer', 'smartphone', 'technologie'),
  ('processeur', 'carte mère', 'cpu', 'motherboard', 'technologie'),
  ('carte graphique', 'carte son', 'gpu', 'sound card', 'technologie'),
  ('mémoire vive', 'stockage', 'ram', 'storage', 'technologie'),
  ('disque dur', 'clé usb', 'hard drive', 'usb key', 'technologie'),
  ('clavier', 'souris', 'keyboard', 'mouse', 'technologie'),
  ('écran', 'projecteur', 'monitor', 'projector', 'technologie'),
  ('webcam', 'micro', 'webcam', 'microphone', 'technologie'),
  ('routeur', 'modem', 'router', 'modem', 'technologie'),
  ('fibre', 'ethernet', 'fiber', 'ethernet', 'technologie'),
  ('wifi', 'bluetooth', 'wifi', 'bluetooth', 'technologie'),
  ('serveur', 'client', 'server', 'client', 'technologie'),
  ('base de données', 'requête', 'database', 'query', 'technologie'),
  ('frontend', 'backend', 'frontend', 'backend', 'technologie'),
  ('api', 'webhook', 'api', 'webhook', 'technologie'),
  ('navigateur', 'onglet', 'browser', 'tab', 'technologie'),
  ('moteur de recherche', 'index', 'search engine', 'index', 'technologie'),
  ('système', 'fichier', 'system', 'file', 'technologie'),
  ('algorithme', 'donnée', 'algorithm', 'data', 'technologie'),
  ('variable', 'constante', 'variable', 'constant', 'technologie'),
  ('boucle', 'condition', 'loop', 'condition', 'technologie'),
  ('fonction', 'module', 'function', 'module', 'technologie'),
  ('objet', 'classe', 'object', 'class', 'technologie'),
  ('commit', 'branche', 'commit', 'branch', 'technologie'),
  ('merge', 'conflit', 'merge', 'conflict', 'technologie'),
  ('test', 'déploiement', 'test', 'deployment', 'technologie'),
  ('conteneur', 'image', 'container', 'image', 'technologie'),
  ('dockerfile', 'registry', 'dockerfile', 'registry', 'technologie'),
  ('cluster', 'kubernetes', 'cluster', 'kubernetes', 'technologie'),
  ('microservice', 'gateway', 'microservice', 'gateway', 'technologie'),
  ('jeton', 'session', 'token', 'session', 'technologie'),
  ('chiffrement', 'clé', 'encryption', 'key', 'technologie'),
  ('hachage', 'sel', 'hash', 'salt', 'technologie'),
  ('pare-feu', 'antivirus', 'firewall', 'antivirus', 'technologie'),
  ('backup', 'restauration', 'backup', 'restore', 'technologie'),
  ('journal', 'métrique', 'log', 'metric', 'technologie'),
  ('capteur', 'iot', 'sensor', 'iot', 'technologie'),
  ('drone', 'télécommande', 'drone', 'remote', 'technologie'),
  ('robot', 'servo', 'robot', 'servo', 'technologie'),
  ('imprimante 3d', 'filament', '3d printer', 'filament', 'technologie'),
  ('casque vr', 'contrôleur', 'vr headset', 'controller', 'technologie'),
  ('lunettes ar', 'affichage', 'ar glasses', 'display', 'technologie'),
  ('assistant vocal', 'commande', 'voice assistant', 'command', 'technologie'),
  ('reconnaissance vocale', 'transcription', 'speech recognition', 'transcription', 'technologie'),
  ('vision par ordinateur', 'caméra', 'computer vision', 'camera', 'technologie'),
  ('réseau de neurones', 'dataset', 'neural network', 'dataset', 'technologie'),
  ('annotation', 'pipeline', 'annotation', 'pipeline', 'technologie'),
  ('ci', 'cd', 'ci', 'cd', 'technologie'),
  ('tableur', 'diaporama', 'spreadsheet', 'slideshow', 'technologie'),
  ('mail', 'messagerie', 'email', 'messaging', 'technologie'),

  -- Divertissement (50)
  ('film', 'popcorn', 'movie', 'popcorn', 'divertissement'),
  ('série', 'épisode', 'series', 'episode', 'divertissement'),
  ('documentaire', 'caméra', 'documentary', 'camera', 'divertissement'),
  ('dessin animé', 'voix', 'cartoon', 'voice', 'divertissement'),
  ('théâtre', 'scène', 'theater', 'stage', 'divertissement'),
  ('comédie', 'stand-up', 'comedy', 'stand-up', 'divertissement'),
  ('musique', 'concert', 'music', 'concert', 'divertissement'),
  ('guitare', 'piano', 'guitar', 'piano', 'divertissement'),
  ('batterie', 'basse', 'drums', 'bass', 'divertissement'),
  ('orchestre', 'symphonie', 'orchestra', 'symphony', 'divertissement'),
  ('opéra', 'aria', 'opera', 'aria', 'divertissement'),
  ('ballet', 'tutu', 'ballet', 'tutu', 'divertissement'),
  ('cirque', 'acrobate', 'circus', 'acrobat', 'divertissement'),
  ('magie', 'illusion', 'magic', 'illusion', 'divertissement'),
  ('spectacle', 'lumière', 'show', 'light', 'divertissement'),
  ('festival', 'billet', 'festival', 'ticket', 'divertissement'),
  ('musée', 'exposition', 'museum', 'exhibit', 'divertissement'),
  ('galerie', 'peinture', 'gallery', 'painting', 'divertissement'),
  ('livre', 'roman', 'book', 'novel', 'divertissement'),
  ('bande dessinée', 'planche', 'comic', 'panel', 'divertissement'),
  ('jeu de plateau', 'dé', 'board game', 'die', 'divertissement'),
  ('carte', 'poker', 'card', 'poker', 'divertissement'),
  ('échecs', 'dames', 'chess', 'checkers', 'divertissement'),
  ('puzzle', 'pièce', 'puzzle', 'piece', 'divertissement'),
  ('escape game', 'énigme', 'escape room', 'riddle', 'divertissement'),
  ('quiz', 'buzzer', 'quiz', 'buzzer', 'divertissement'),
  ('karaoké', 'micro', 'karaoke', 'microphone', 'divertissement'),
  ('danse', 'salsa', 'dance', 'salsa', 'divertissement'),
  ('roller', 'skate', 'roller', 'skate', 'divertissement'),
  ('parc attraction', 'looping', 'theme park', 'loop', 'divertissement'),
  ('montagne russe', 'virage', 'roller coaster', 'turn', 'divertissement'),
  ('bowling', 'quille', 'bowling', 'pin', 'divertissement'),
  ('billard', 'queue', 'billiards', 'cue', 'divertissement'),
  ('fléchette', 'cible', 'dart', 'target', 'divertissement'),
  ('console', 'manette', 'console', 'controller', 'divertissement'),
  ('jeu vidéo', 'niveau', 'video game', 'level', 'divertissement'),
  ('arcade', 'joystick', 'arcade', 'joystick', 'divertissement'),
  ('réalité virtuelle', 'immersion', 'virtual reality', 'immersion', 'divertissement'),
  ('maquette', 'colle', 'model', 'glue', 'divertissement'),
  ('lego', 'brique', 'lego', 'brick', 'divertissement'),
  ('jardinage', 'potager', 'gardening', 'vegetable patch', 'divertissement'),
  ('cuisine', 'pâtisserie', 'cooking', 'pastry', 'divertissement'),
  ('cocktail', 'shaker', 'cocktail', 'shaker', 'divertissement'),
  ('dégustation', 'vin', 'tasting', 'wine', 'divertissement'),
  ('camping', 'feu camp', 'camping', 'campfire', 'divertissement'),
  ('pêche', 'canne', 'fishing', 'rod', 'divertissement'),
  ('randonnée', 'sac', 'hiking', 'backpack', 'divertissement'),
  ('photographie', 'objectif', 'photography', 'lens', 'divertissement'),
  ('tournage', 'clap', 'shooting', 'clapper', 'divertissement'),
  ('podcast', 'casque', 'podcast', 'headset', 'divertissement');
